######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 4 11:40:28 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += diskusage.cpp
