######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 12 18:28:17 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += birthdays.cpp
