######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 25 14:54:51 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += educational.h entertainment.h film.h filmlist.h
SOURCES += educational.cpp \
           entertainment.cpp \
           film.cpp \
           filmClient.cpp \
           filmlist.cpp
