######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 25 15:00:06 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += library.h libraryui.h
SOURCES += library.cpp libraryClient-v2.cpp libraryui.cpp
