######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 19 19:12:37 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myfirstgui.h
SOURCES += main.cpp myfirstgui.cpp
